version: '3'

services:
  dev:
    container_name: adote-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    ports:
      - '3000:3000'
    command: yarn dev
    volumes:
      - 'usr/app/node_modules'
      - './:/usr/app'
  postgres:
    container_name: adotedb
    image: postgres:13-alpine3.14
    restart: always
    environment:
      POSTGRES_USERNAME: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'adotedb'
    ports:
      - '5432:5432'
    volumes:
      - 'adotedb:/var/lib/postgresql/data'

volumes:
  adotedb:
