version: '3'

services:
  api:
    build:
      context: ./
    env_file: .env.prod
    ports:
      - '8080:8080'
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '80:80'
