version: '3'

services:
  dev:
    container_name: adote-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: .env
    ports:
      - '3000:3000'
    command: yarn dev
    volumes:
      - 'usr/app/node_modules'
      - './:/usr/app'
